linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - unparam
    - prealloc
    - nakedret
    - maligned
    - funlen
    - godox
    - wsl
    - gocognit
    - gomnd
    - godot
    - nolintlint
    - goerr113
    - testpackage
    - gosec
    - nestif
  fast: false
