apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: virtualservices.networking.kolonial.no
spec:
  group: networking.kolonial.no
  names:
    kind: VirtualService
    plural: virtualservices
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            gateways:
              items:
                type: string
              type: array
            hosts:
              items:
                type: string
              type: array
            http:
              items:
                properties:
                  match:
                    items:
                      properties:
                        uri:
                          properties:
                            prefix:
                              type: string
                          required:
                          - prefix
                          type: object
                      required:
                      - uri
                      type: object
                    type: array
                  redirect:
                    properties:
                      uri:
                        type: string
                    required:
                    - uri
                    type: object
                  route:
                    items:
                      properties:
                        destination:
                          properties:
                            host:
                              type: string
                            port:
                              properties:
                                number:
                                  format: int64
                                  type: integer
                              required:
                              - number
                              type: object
                          required:
                          - host
                          - port
                          type: object
                      required:
                      - destination
                      type: object
                    type: array
                  websocketUpgrade:
                    type: boolean
                required:
                - match
                - websocketUpgrade
                type: object
              type: array
          required:
          - hosts
          - http
          type: object
        status:
          type: object
  version: v1alpha3
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
